### ISSUE TITLE
Debug mode is set to TRUE

### ISSUE THREAD

**Issue by gokulakrishnanbalaji** [Karthikrajatp/Book-Exchanging-System#1]
Inside the app.run() function, debug is given a TRUE boolean value, which is recommended in production phase, but not in deployment phase which may affect the quality of the deployed app.

Current:
`app.run(debug=TRUE)`

Required:
`app.run()`

**Comment by gokulakrishnanbalaji** [comment]
Can I work on this issue?

**Comment by gokulakrishnanbalaji** [comment]
@Karthikrajatp I have created a pull request #2 . Kindly review it and add it to the source code. Thus, we can close this issue.

**Comment by Karthikrajatp** [comment]
Review done and successfully merged!!
